export const ADDBOOK='ADDBOOK';
export const SUBTRACTISSUEBOOK='SUBTRACTISSUEBOOK';
export const RETURNDATA='RETURNDATA';
export const DELETEROW='DELETEROW';
export const ADD_RETURN_BOOK="ADD_RETURN_BOOK";

