export const BOOKISSUECHECK="BOOKISSUECHECK";
export const TOTALISSUEDATAINSTUDENT="TOTALISSUEDATAINSTUDENT";
export const REMOVE_RETURNED_BOOK_DATA_STUDENTLIST="REMOVE_RETURNED_BOOK_DATA_STUDENTLIST";



